/*
 * System_Recorder.c
 *
 *  Created on: Mar 28, 2024
 *      Author: ADMIN
 */

#include "System_Recorder.h"


FUNCTION_StatusTypeDef _Erase_Sector (uint32_t Address)
{
    /* Unprotect sector in main memory with ECC generated by hardware */
    DL_FlashCTL_unprotectSector(FLASHCTL, Address, DL_FLASHCTL_REGION_SELECT_MAIN);

    /* Erase sector in main memory */
    DL_FlashCTL_eraseMemoryFromRAM(FLASHCTL, Address, DL_FLASHCTL_COMMAND_SIZE_SECTOR);
    return FUNCTION_OK;
}

FUNCTION_StatusTypeDef _Recorder_Execution (RecorderPackageTypeDef* writePackage, uint32_t globalTime, Operating_Mode* stateOfCharger)
{
    const uint16_t VDDCHRG_ADC  = (uint16_t)(VDDCHRG/VBAT_GAIN);
    static Operating_Mode lastStateOfCharger;
    static bool MemoryArrangeFlag = false;

    if ((*stateOfCharger != lastStateOfCharger) && _Is_Memory_Blank(writePackage->Address) && (writePackage->writeFlag == true)) {

        /* Cho phep sap xep lai bo nho neu day */
        MemoryArrangeFlag = false;

        /* Truong hop dang sac nhung rut jack dau ra khoi ac-quy */
        if (((lastStateOfCharger == MODE_PRECHARGE) || (lastStateOfCharger == MODE_BULK_CHARGE)) && (*stateOfCharger == MODE_BATTERY_CHECK) && (writePackage->chargeTime > 60U)) {
            DL_TimerG_stopCounter(ISRTIMER_INST);

            writePackage->Address -= 16U;
            writePackage->typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
            _Write_Data_To_Flash(writePackage->Address, *writePackage);
            _Write_Package_Refresh(writePackage);
            lastStateOfCharger = *stateOfCharger;

            DL_TimerG_startCounter(ISRTIMER_INST);
        }
        /* Truong hop dang sac nhung rut nguon */
        else if (((lastStateOfCharger == MODE_PRECHARGE) || (lastStateOfCharger == MODE_BULK_CHARGE)) && (*stateOfCharger == MODE_OVP) && (writePackage->chargeTime > 60U)) {
            DL_TimerG_stopCounter(ISRTIMER_INST);

            writePackage->Address -= 16U;
            writePackage->typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
            _Write_Data_To_Flash(writePackage->Address, *writePackage);
            _Write_Package_Refresh(writePackage);
            lastStateOfCharger = *stateOfCharger;

            DL_TimerG_startCounter(ISRTIMER_INST);
        }
        /* Truong hop dang sac day */
        else if (*stateOfCharger == MODE_FULLY_CHARGED) {
            DL_TimerG_stopCounter(ISRTIMER_INST);

            writePackage->Address -= 16U;
            writePackage->typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
            writePackage->writeFlag = false;
            _Write_Data_To_Flash(writePackage->Address, *writePackage);
            _Write_Package_Refresh(writePackage);
            lastStateOfCharger = *stateOfCharger;

            DL_TimerG_startCounter(ISRTIMER_INST);
        }
        /* Truong hop dang sac nhung phat hien ra loi */
        else if (*stateOfCharger == MODE_OFP) {
             DL_TimerG_stopCounter(ISRTIMER_INST);

             writePackage->Address -= 16U;
             writePackage->typeOfPackage = TYPE_OF_PACKAGE_ERROR_MODE;
             writePackage->errorMode = ERR_HARDWARE;
             _Write_Data_To_Flash(writePackage->Address, *writePackage);
             _Write_Package_Refresh(writePackage);
             lastStateOfCharger = *stateOfCharger;

             DL_TimerG_startCounter(ISRTIMER_INST);
        }
        /* Truong hop dang sac nhung bi bao ve qua dong, qua ap, qua thoi gian sac*/
        else if ((*stateOfCharger == MODE_OCP1) || (*stateOfCharger == MODE_OCP2) || (*stateOfCharger == MODE_OVP) || (*stateOfCharger == MODE_OT)) {
             DL_TimerG_stopCounter(ISRTIMER_INST);

             if (*stateOfCharger == MODE_OT) {
                 writePackage->typeOfPackage = TYPE_OF_PACKAGE_ERROR_MODE;

                 if (writePackage->lastVbat < VDDCHRG_ADC) {
                     writePackage->protectionMode = ERR_PRECHARGE_TIMEOUT;
                 }
                 else {
                     writePackage->protectionMode = ERR_CHARGE_TIMEOUT;
                 }
             }
             else {
                 writePackage->typeOfPackage = TYPE_OF_PACKAGE_PROTECTION_MODE;
                 writePackage->protectionMode = *stateOfCharger;
             }

             /* Kiem tra xem du lieu da duoc ghi hay chua */
             if ((writePackage->initialVbat != 0U) && (writePackage->lastVbat != 0U)) {
                 writePackage->Address -= 16U;
                 _Write_Data_To_Flash(writePackage->Address, *writePackage);
                 _Write_Package_Refresh(writePackage);
             }
             lastStateOfCharger = *stateOfCharger;

             DL_TimerG_startCounter(ISRTIMER_INST);
        }
        /* Truong hop dang sac nhung bi bao ve qua nhiet */
        else if (*stateOfCharger == MODE_OTP) {
            DL_TimerG_stopCounter(ISRTIMER_INST);

            writePackage->Address -= 16U;
            writePackage->typeOfPackage = TYPE_OF_PACKAGE_PROTECTION_MODE;
            writePackage->protectionMode = MODE_OTP;
            _Write_Data_To_Flash(writePackage->Address, *writePackage);
            _Write_Package_Refresh(writePackage);
            lastStateOfCharger = *stateOfCharger;

            DL_TimerG_startCounter(ISRTIMER_INST);
         }

//        else if ((*stateOfCharger == MODE_IVP) && ((lastStateOfCharger == MODE_PRECHARGE) || (lastStateOfCharger == MODE_BULK_CHARGE))) {
//            DL_TimerG_stopCounter(ISRTIMER_INST);
//
//            writePackage->Address -= 16U;
//            writePackage->typeOfPackage = TYPE_OF_PACKAGE_PROTECTION_MODE;
//            writePackage->protectionMode = MODE_IVP;
//            _Write_Data_To_Flash(writePackage->Address, *writePackage);
//            _Write_Package_Refresh(writePackage);
//            lastStateOfCharger = *stateOfCharger;
//
//            DL_TimerG_startCounter(ISRTIMER_INST);
//        }
    }

    if (!_Is_Memory_Blank(writePackage->Address) && (MemoryArrangeFlag == false)) {
        DL_TimerG_stopCounter(ISRTIMER_INST);
        _Rearrage_Memory();

        writePackage->Address = 0x63FF;
        MemoryArrangeFlag = true;
        DL_TimerG_startCounter(ISRTIMER_INST);
    }

    lastStateOfCharger = *stateOfCharger;

    return FUNCTION_OK;
}

FUNCTION_StatusTypeDef _Write_Data_To_Flash (uint32_t Address, RecorderPackageTypeDef writePackage)
{
    uint32_t packagingResultHigh[2];
    uint32_t packagingResultLow[2];

    /* -----------------------------Recorded data packaging--------------------------- */
    if (writePackage.typeOfPackage == 0x00) { // Normal Mode Package
        /* first 32bit of recording package */
        packagingResultHigh[1] = (writePackage.typeOfPackage << 30U) | (writePackage.initialVbat << 18U) | (writePackage.lastVbat << 6U) | (writePackage.maxTemperature >> 6U);
        packagingResultHigh[0] = ((writePackage.maxTemperature & 0xFFF) << 26U) | (writePackage.prechargeTime << 11U) | (writePackage.chargeTime >> 5U);

        /* last 32bit of recording package */
        packagingResultLow[1] = ((writePackage.chargeTime & 0x1F) << 27U) | (writePackage.internalResistor << 10U) | (writePackage.stateOfCharge >> 32U);
        packagingResultLow[0] = (writePackage.stateOfCharge & 0xFFFFFFF);
    }
    else if (writePackage.typeOfPackage == 0x01) { // Error Mode Package
        /* first 32bit of recording package */
        packagingResultHigh[1] = (writePackage.typeOfPackage << 30U) | (writePackage.initialVbat << 18U) | (writePackage.lastVbat << 6U) | (writePackage.errorMode >> 6U);
        packagingResultHigh[0] = ((writePackage.errorMode & 0xFFF) << 26U) | (writePackage.prechargeTime << 11U) | (writePackage.chargeTime >> 5U);

        /* last 32bit of recording package */
        packagingResultLow[1] = ((writePackage.chargeTime & 0x1F) << 27U) | (writePackage.internalResistor << 10U) | (writePackage.stateOfCharge >> 32U);
        packagingResultLow[0] = (writePackage.stateOfCharge & 0xFFFFFFF);
    }
    else if (writePackage.typeOfPackage == 0x02) { // Protection Mode Package
        /* first 32bit of recording package */
        packagingResultHigh[1] = (writePackage.typeOfPackage << 30U) | (writePackage.initialVbat << 18U) | (writePackage.lastVbat << 6U) | (writePackage.protectionMode >> 6U);
        packagingResultHigh[0] = ((writePackage.protectionMode & 0xFFF) << 26U) | (writePackage.prechargeTime << 11U) | (writePackage.chargeTime >> 5U);

        /* last 32bit of recording package */
        packagingResultLow[1] = ((writePackage.chargeTime & 0x1F) << 27U) | (writePackage.internalResistor << 10U) | (writePackage.stateOfCharge >> 32U);
        packagingResultLow[0] = (writePackage.stateOfCharge & 0xFFFFFFF);
    }

    /* -----------------------------Write to flash--------------------------- */
    /* 64-bit write to flash in main memory */
    DL_FlashCTL_unprotectSector(FLASHCTL, Address, DL_FLASHCTL_REGION_SELECT_MAIN);
    DL_FlashCTL_programMemoryFromRAM64WithECCGenerated(FLASHCTL, (Address), &packagingResultHigh[0]);

    /* 64-bit write to flash in main memory */
    DL_FlashCTL_unprotectSector(FLASHCTL, Address - 8U, DL_FLASHCTL_REGION_SELECT_MAIN);
    DL_FlashCTL_programMemoryFromRAM64WithECCGenerated(FLASHCTL, (Address - 8U), &packagingResultLow[0]);

    return FUNCTION_OK;
}


FUNCTION_StatusTypeDef _Recorder_Check(RecorderPackageTypeDef* readPackage, Operating_Mode* printSavedState)
{
    uint64_t readingResult64bitHigh;
    uint64_t readingResult64bitLow;
    uint64_t packageCode;
    uint32_t Address = CHRG_DATA_READ_BASE_ADDRESS;
    uint32_t savedPrintAddress = Address;

    while(Address >= CHRG_DATA_READ_STOP_ADDRESS ) {
        readingResult64bitHigh = _READ_DATA_FROM(Address);
        readingResult64bitLow = _READ_DATA_FROM(Address - 8U);
        packageCode = readingResult64bitHigh >> 62U;

        if (packageCode == TYPE_OF_PACKAGE_NORMAL_MODE) { // Normal Mode Package
            readPackage->Address = Address;
            readPackage->typeOfPackage = packageCode;
            readPackage->initialVbat = (readingResult64bitHigh >> 50U) & 0x0FFF;
            readPackage->lastVbat = (readingResult64bitHigh >> 38U) & 0x0FFF;
            readPackage->maxTemperature = (readingResult64bitHigh >> 26U) & 0x0FFF;
            readPackage->prechargeTime = (readingResult64bitHigh >> 11U) & 0x7FFF;
            readPackage->chargeTime = ((readingResult64bitHigh & 0x7FF) << 5U ) | ((readingResult64bitLow >> 59U) & 0x1F);
            readPackage->internalResistor = (readingResult64bitLow >> 42U) & 0x1FFFF;
            readPackage->stateOfCharge = readingResult64bitLow & 0x0FFFFFFF;
        }
        else if (packageCode == TYPE_OF_PACKAGE_ERROR_MODE) { // Error Mode Package
            readPackage->Address = Address;
            readPackage->typeOfPackage = packageCode;
            readPackage->initialVbat = (readingResult64bitHigh >> 50U) & 0x0FFF;
            readPackage->lastVbat = (readingResult64bitHigh >> 38U) & 0x0FFF;
            readPackage->errorMode = (readingResult64bitHigh >> 26U) & 0x0FFF;
            readPackage->prechargeTime = (readingResult64bitHigh >> 11U) & 0x7FFF;
            readPackage->chargeTime = ((readingResult64bitHigh & 0x7FF) << 5U ) | ((readingResult64bitLow >> 59U) & 0x1F);
            readPackage->internalResistor = (readingResult64bitLow >> 42U) & 0x1FFFF;
            readPackage->stateOfCharge = readingResult64bitLow & 0x0FFFFFFF;
        }
        else if (packageCode == TYPE_OF_PACKAGE_PROTECTION_MODE) { // Protection Mode Package
            readPackage->Address = Address;
            readPackage->typeOfPackage = packageCode;
            readPackage->initialVbat = (readingResult64bitHigh >> 50U) & 0x0FFF;
            readPackage->lastVbat = (readingResult64bitHigh >> 38U) & 0x0FFF;
            readPackage->protectionMode = (readingResult64bitHigh >> 26U) & 0x0FFF;
            readPackage->prechargeTime = (readingResult64bitHigh >> 11U) & 0x7FFF;
            readPackage->chargeTime = ((readingResult64bitHigh & 0x7FF) << 5U ) | ((readingResult64bitLow >> 59U) & 0x1F);
            readPackage->internalResistor = (readingResult64bitLow >> 42U) & 0x1FFFF;
            readPackage->stateOfCharge = readingResult64bitLow & 0x0FFFFFFF;
        }
        else {
            readPackage->Address = Address;
            return FUNCTION_OK;
        }

        if (readPackage->typeOfPackage == TYPE_OF_PACKAGE_NORMAL_MODE) {
            sprintf(txUART,"\r%d, VbatInit: %d, VbatLast: %d, maxTemp: %d, preChargeTime: %d, chargeTime: %d, ESR: %d, SoC: %llu", Address, readPackage->initialVbat,
                    readPackage->lastVbat, readPackage->maxTemperature, readPackage->prechargeTime, readPackage->chargeTime, readPackage->internalResistor, readPackage->stateOfCharge);
        }
        else if (readPackage->typeOfPackage == TYPE_OF_PACKAGE_ERROR_MODE) {
            sprintf(txUART,"\r%d, %s, VbatInit: %d, VbatLast: %d, preChargeTime: %d, chargeTime: %d, ESR: %d, SoC: %llu", Address, _CHRGR_Get_Charger_State(readPackage->errorMode),
                    readPackage->initialVbat, readPackage->lastVbat, readPackage->prechargeTime, readPackage->chargeTime, readPackage->internalResistor, readPackage->stateOfCharge);
            *printSavedState = readPackage->errorMode;
            savedPrintAddress = Address;
        }
        else if (readPackage->typeOfPackage == TYPE_OF_PACKAGE_PROTECTION_MODE) {
            sprintf(txUART,"\r%d, %s, VbatInit: %d, VbatLast: %d, preChargeTime: %d, chargeTime: %d, ESR: %d, SoC: %llu", Address, _CHRGR_Get_Charger_State(readPackage->protectionMode),
                    readPackage->initialVbat, readPackage->lastVbat, readPackage->prechargeTime, readPackage->chargeTime, readPackage->internalResistor, readPackage->stateOfCharge);
            *printSavedState = readPackage->protectionMode;
            savedPrintAddress = Address;
        }

        if (((savedPrintAddress - Address) >> 4U) >= PREVIOUS_SAVED_MODE_READ) {
            *printSavedState = 0;
        }


        //UART Communication Tasks
        if (readPackage->TxFlashDataFlag == true) {
            HAL_transmitUARTMessage(txUART, strlen(txUART));
            delay_cycles(10000000U); //Delay 0.25
        }

        Address = Address - 16U;
    }
    return FUNCTION_OK;
}

FUNCTION_StatusTypeDef _Record_Data_Update(RecorderPackageTypeDef* writePackage, Operating_Mode* stateOfCharger, uint32_t chargeTime10ms)
{

    uint16_t chargeTime1s = (chargeTime10ms*41U)>>12U;

    if (*stateOfCharger == MODE_CHARGING_REQUEST) {
        writePackage->initialVbat = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_VBAT);
    }

    else if (*stateOfCharger == MODE_PRECHARGE) {
        writePackage->lastVbat = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_VBAT);
        writePackage->lastIbat = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_IBAT);
        writePackage->lastTemperature = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_TEMP);

        if (writePackage->lastTemperature > writePackage->maxTemperature) {
            writePackage->maxTemperature = writePackage->lastTemperature;
        }

        writePackage->stateOfCharge += writePackage->lastIbat;
        writePackage->chargeTime = writePackage->prechargeTime = chargeTime1s;
    }
    else if (*stateOfCharger == MODE_BULK_CHARGE) {
        writePackage->lastVbat = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_VBAT);
        writePackage->lastIbat = DL_ADC12_getMemResult(ADC12_0_INST, ADC12_0_ADCMEM_IBAT);
        writePackage->stateOfCharge += writePackage->lastIbat;
        writePackage->chargeTime = chargeTime1s;
    }
    else if (*stateOfCharger == MODE_BATTERY_CHECK) {
        writePackage->writeFlag = true;
    }

    return FUNCTION_OK;
}

FUNCTION_StatusTypeDef _Write_Package_Refresh(RecorderPackageTypeDef* writePackage)
{
    writePackage->typeOfPackage = 0U;
    writePackage->initialVbat = 0U;
    writePackage->lastVbat = 0U;
    writePackage->lastIbat = 0U;
    writePackage->maxTemperature = 0U;
    writePackage->prechargeTime = 0U;
    writePackage->chargeTime = 0U;
    writePackage->internalResistor = 0U;
    writePackage->stateOfCharge = 0U;
    writePackage->protectionMode = 0U;
    writePackage->errorMode = 0U;

    return FUNCTION_OK;
}

bool _Is_Memory_Blank(uint32_t Address)
{
    if (Address - 16U >= CHRG_DATA_WRITE_STOP_ADDRESS) {
        return true;
    }
    else return false;
}

void _Read_Mode_Test (RecorderPackageTypeDef writePackage)
{

    writePackage.Address = CHRG_DATA_WRITE_BASE_ADDRESS;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_ERROR_MODE;
    writePackage.errorMode = ERR_HARDWARE;
    _Write_Data_To_Flash(writePackage.Address, writePackage);

    writePackage.Address -= 16U;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
    _Write_Data_To_Flash(writePackage.Address, writePackage);

    writePackage.Address -= 16U;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
    _Write_Data_To_Flash(writePackage.Address, writePackage);

    writePackage.Address -= 16U;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
    _Write_Data_To_Flash(writePackage.Address, writePackage);

    writePackage.Address -= 16U;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_PROTECTION_MODE;
    writePackage.protectionMode = MODE_OVP;
    _Write_Data_To_Flash(writePackage.Address, writePackage);

    writePackage.Address -= 16U;
    writePackage.typeOfPackage = TYPE_OF_PACKAGE_NORMAL_MODE;
    _Write_Data_To_Flash(writePackage.Address, writePackage);
}

void _Rearrage_Memory(void)
{
    /* Mode Sector 3 -> 2 */
    _Move_Data_From_Sector_to_Sector(0x77FF, 0x7BFF);

    /* Mode Sector 4 -> 3 */
    _Move_Data_From_Sector_to_Sector(0x73FF, 0x77FF);

    /* Mode Sector 5 -> 4 */
    _Move_Data_From_Sector_to_Sector(0x6FFF, 0x73FF);

    /* Mode Sector 6 -> 5 */
    _Move_Data_From_Sector_to_Sector(0x6BFF, 0x6FFF);

    /* Mode Sector 7 -> 6 */
    _Move_Data_From_Sector_to_Sector(0x67FF, 0x6BFF);

    /* Mode Sector 8 -> 7 */
    _Move_Data_From_Sector_to_Sector(0x63FF, 0x67FF);
}

void _Move_Data_From_Sector_to_Sector (uint32_t writeAddressOfOriginSector, uint32_t writeAddressOfDestinationSector)
{
    uint64_t readingResult64bitHigh = 0U;
    uint64_t readingResult64bitLow = 0U;

   uint32_t packagingResultHigh[2] = {0U};
   uint32_t packagingResultLow[2] = {0U};

   uint32_t readAddress = writeAddressOfOriginSector - 0x07;
   uint32_t writeAddress = writeAddressOfDestinationSector;


   /* Delete Destination Sector */
   _Erase_Sector(writeAddressOfDestinationSector);

   while (writeAddress > writeAddressOfOriginSector)
   {
       readingResult64bitHigh = _READ_DATA_FROM(readAddress);
       readingResult64bitLow = _READ_DATA_FROM(readAddress - 8U);
       packagingResultHigh[1] = readingResult64bitHigh >> 32U;
       packagingResultHigh[0] = (uint32_t)(readingResult64bitHigh);

       packagingResultLow[1] = readingResult64bitLow >> 32U;
       packagingResultLow[0] = (uint32_t)(readingResult64bitLow);

       /* -----------------------------Write to flash--------------------------- */
       /* 64-bit write to flash in main memory */
       DL_FlashCTL_unprotectSector(FLASHCTL, writeAddress, DL_FLASHCTL_REGION_SELECT_MAIN);
       DL_FlashCTL_programMemoryFromRAM64WithECCGenerated(FLASHCTL, (writeAddress), &packagingResultHigh[0]);

       /* 64-bit write to flash in main memory */
       DL_FlashCTL_unprotectSector(FLASHCTL, writeAddress - 8U, DL_FLASHCTL_REGION_SELECT_MAIN);
       DL_FlashCTL_programMemoryFromRAM64WithECCGenerated(FLASHCTL, (writeAddress - 8U), &packagingResultLow[0]);
       writeAddress -= 16U;
       readAddress -= 16U;
   }

   _Erase_Sector(writeAddressOfOriginSector);

}
